### ISSUE TITLE
Local Environment Setup 💻 

### ISSUE THREAD

**Issue by jackwotherspoon** [kiranwoth/expense-tracker#1]
Hey @kiranwoth  assigning you your first "before we begin" type task! 

Let's make sure your local setup is ready for development 😄 

Couple things to setup (check these off as you go):
- [x] Download an IDE (if you already have one then woo!, I like [vscode](https://code.visualstudio.com/) personally as it feature rich but minimal) 
- [x] Get Python installed on your computer (we will use Python as the backend of our app unless you prefer a different language, feel free to comment on here if you don't want to use Python 😄) I would recommend using [pyenv](https://github.com/pyenv/pyenv) to manage your Python installations as it allows you to easily switch Python versions on the fly.
- [x] Get familiar with Github a little. Run through [the quickstart](https://docs.github.com/en/get-started/quickstart) to get Git downloaded on your computer and maybe try cloning this repo and pushing a "test" commit by adding a `test.txt` file with "Hello World!" on the first line 🚀 
- [x] Optional: If you are not super comfortable with Python it is not a problem, we will go at whatever pace you want and learn as we go. A good hour tutorial to get the basics of Python that I like is [this video on youtube](https://www.youtube.com/watch?v=kqtD5dpn9C8).

When your done just close out this issue! Then we can start discussing more tasks and break them down into really small pieces. Feel free to comment here and at me @jackwotherspoon if you have any questions along the way or get stuck :smile:

**Comment by kiranwoth** [comment]
@jackwotherspoon should commits not be on the main branch?

**Comment by jackwotherspoon** [comment]
Great question! Normally no, I see you created a branch which is perfect 😄 Normally you want to create a branch for feature or dev work and then open a pull request to the main branch so someone can review your code prior to merging it. 

You can make this easier by disabling commits directly on the main branch. To do so, go to the repository "Settings" tab and then under "Branches" you can add a branch protection rule to `main` branch to require pull requests and disable merging directly to main.
