### ISSUE TITLE
Read: `@app.get("/expenses/")` endpoint to get all expenses

### ISSUE THREAD

**Issue by jackwotherspoon** [kiranwoth/expense-tracker#14]
See linked issue for full details

**Comment by kiranwoth** [comment]
@jackwotherspoon I'm not doing query parameters yet right? this is just supposed to return the whole expenses dictionary right now

**Comment by jackwotherspoon** [comment]
> @jackwotherspoon I'm not doing query parameters yet right? this is just supposed to return the whole expenses dictionary right now

Correct, no need for query parameters yet, we can add those as part of the database integration work
