### ISSUE TITLE
Delete `@app.delete("/expenses/{id}")` endpoint to delete an expense by ID

### ISSUE THREAD

**Issue by jackwotherspoon** [kiranwoth/expense-tracker#17]
See linked issue for full details

**Comment by kiranwoth** [comment]
What is this supposed to return? Do you return nothing or the expense you delete?
Or should it be something else like True/False for if it worked or not

**Comment by jackwotherspoon** [comment]
Usually I've seen a `204` status code (which means success but return "No content") is sent on a successful deletion.

Something like
```python
from fastapi import FastAPI, HTTPException, Response, status

# ... 
return Response(status_code=status.HTTP_204_NO_CONTENT)
```
