### ISSUE TITLE
Decide on Database type to use 🗄️ 🧑‍💻 

### ISSUE THREAD

**Issue by jackwotherspoon** [kiranwoth/expense-tracker#27]
We need to figure out what type of database we want to use for integration with our app.

SQLite is probably the easiest:
> SQLite is probably the most straightforward database to connect to with a Python application since you don't need to install any external Python SQL modules to do so. By default, your Python installation contains a Python SQL library named sqlite3.

SQLite also works with [`SQLAlchemy`](https://docs.sqlalchemy.org/en/20/core/engines.html#sqlite) which is a Python database ORM framework that integrates nicely with FastAPI and our current setup.

Unless you want to try a different database or have experience with a different one I say we go with SQLite.

**Comment by kiranwoth** [comment]
SQLite sounds good

**Comment by jackwotherspoon** [comment]
SQLite it is ✅
