### ISSUE TITLE
Research desired Python back-end framework 🐍 🔙 

### ISSUE THREAD

**Issue by jackwotherspoon** [kiranwoth/expense-tracker#4]
Hey @kiranwoth,

This task is more of a research task. We should decide on a Python web framework to use for the backend functionality of our app. The backend being the code that will manage and do all the work to `Create`, `Read`, `Update` and `Delete` our expenses being tracked. 

There are two candidates that I think are probably best for scenario (i.e. easy to learn, valuable in industry, etc.):

- [FastAPI](https://fastapi.tiangolo.com/lo/)
- [Flask](https://flask.palletsprojects.com/en/2.3.x/)

Flask is probably the most widely used and has been around for a while. While FastAPI is a new more modern framework that is more performant, easier to learn, and gaining traction in the Python community.

Here is a good article comparing the two: [FastAPI vs Flask](https://www.turing.com/kb/fastapi-vs-flask-a-detailed-comparison#pros-and-cons-of-fastapi-and-flask)

Give the article a read and maybe take a peak at both frameworks and see if there is one that interests you to try (I think both are good options for a resume, although FastAPI might give you more to talk about as it is a new and shiny framework getting a lot of attention these days so might stick out a little more on a resume). Let me know which one you like and we can move forward with it 😄

**Comment by kiranwoth** [comment]
@jackwotherspoon I think I'd like us to use FastAPI. Honestly I wasn't really sure which to choose after reading about them and so I just flipped a coin.
